// Auto-generated Wails bindings — re-exported for clean imports.
// These are generated by `wails dev` / `wails build` into wailsjs/go/app/App.js

// Vault
export { GetCurrentVault, OpenVault, CloseVault, SelectFolder } from '../../wailsjs/go/app/App'
export { GetVaultConfig, SetVaultConfig } from '../../wailsjs/go/app/App'
export { ScanVault, RescanVault } from '../../wailsjs/go/app/App'

// Files
export { GetFiles, GetFileByID, UpdateFile, SearchFiles } from '../../wailsjs/go/app/App'

// Folders
export { GetFolderTree } from '../../wailsjs/go/app/App'

// Tags
export { GetTags, CreateTag, UpdateTag, DeleteTag, GetTagFileCount, GetAllTagFileCounts } from '../../wailsjs/go/app/App'
export { AddTagToFile, RemoveTagFromFile, GetFileTags } from '../../wailsjs/go/app/App'

// Metadata
export { GetFileMetadata, GetBatchMetadata } from '../../wailsjs/go/app/App'

// Thumbnails
export { GenerateThumbnail, GenerateThumbnailsPool, CancelThumbnailGeneration, GetThumbnailData, CleanupOrphanThumbnails } from '../../wailsjs/go/app/App'

// Excluded Folders
export { GetExcludedFolders, AddExcludedFolder, RemoveExcludedFolder } from '../../wailsjs/go/app/App'
