// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExcludedFolder(arg1) {
  return window['go']['app']['App']['AddExcludedFolder'](arg1);
}

export function AddTagToFile(arg1, arg2) {
  return window['go']['app']['App']['AddTagToFile'](arg1, arg2);
}

export function AddTagsToFiles(arg1, arg2) {
  return window['go']['app']['App']['AddTagsToFiles'](arg1, arg2);
}

export function CancelThumbnailGeneration() {
  return window['go']['app']['App']['CancelThumbnailGeneration']();
}

export function CheckFFmpeg() {
  return window['go']['app']['App']['CheckFFmpeg']();
}

export function CleanupOrphanThumbnails() {
  return window['go']['app']['App']['CleanupOrphanThumbnails']();
}

export function CloseVault() {
  return window['go']['app']['App']['CloseVault']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['app']['App']['CopyImageToClipboard'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['app']['App']['CreateTag'](arg1);
}

export function CreateVault(arg1, arg2) {
  return window['go']['app']['App']['CreateVault'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteOriginalFile(arg1) {
  return window['go']['app']['App']['DeleteOriginalFile'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['app']['App']['DeleteTag'](arg1);
}

export function GenerateThumbnail(arg1) {
  return window['go']['app']['App']['GenerateThumbnail'](arg1);
}

export function GenerateThumbnailsForFiles(arg1) {
  return window['go']['app']['App']['GenerateThumbnailsForFiles'](arg1);
}

export function GenerateThumbnailsPool() {
  return window['go']['app']['App']['GenerateThumbnailsPool']();
}

export function GetAllTagFileCounts() {
  return window['go']['app']['App']['GetAllTagFileCounts']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAppSettings() {
  return window['go']['app']['App']['GetAppSettings']();
}

export function GetBatchMetadata(arg1) {
  return window['go']['app']['App']['GetBatchMetadata'](arg1);
}

export function GetCurrentVault() {
  return window['go']['app']['App']['GetCurrentVault']();
}

export function GetExcludedFolders() {
  return window['go']['app']['App']['GetExcludedFolders']();
}

export function GetFileByID(arg1) {
  return window['go']['app']['App']['GetFileByID'](arg1);
}

export function GetFileMetadata(arg1) {
  return window['go']['app']['App']['GetFileMetadata'](arg1);
}

export function GetFileTags(arg1) {
  return window['go']['app']['App']['GetFileTags'](arg1);
}

export function GetFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetFiles'](arg1, arg2, arg3, arg4);
}

export function GetFolderTree(arg1) {
  return window['go']['app']['App']['GetFolderTree'](arg1);
}

export function GetLastVaultPath() {
  return window['go']['app']['App']['GetLastVaultPath']();
}

export function GetOriginalFilePath(arg1) {
  return window['go']['app']['App']['GetOriginalFilePath'](arg1);
}

export function GetRecentVaults() {
  return window['go']['app']['App']['GetRecentVaults']();
}

export function GetTagAliases(arg1) {
  return window['go']['app']['App']['GetTagAliases'](arg1);
}

export function GetTagFileCount(arg1) {
  return window['go']['app']['App']['GetTagFileCount'](arg1);
}

export function GetTags(arg1) {
  return window['go']['app']['App']['GetTags'](arg1);
}

export function GetThumbnailData(arg1) {
  return window['go']['app']['App']['GetThumbnailData'](arg1);
}

export function GetThumbnailInfo(arg1) {
  return window['go']['app']['App']['GetThumbnailInfo'](arg1);
}

export function GetThumbnailPath(arg1) {
  return window['go']['app']['App']['GetThumbnailPath'](arg1);
}

export function GetVaultConfig() {
  return window['go']['app']['App']['GetVaultConfig']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function OpenFileFolder(arg1) {
  return window['go']['app']['App']['OpenFileFolder'](arg1);
}

export function OpenOriginalFile(arg1) {
  return window['go']['app']['App']['OpenOriginalFile'](arg1);
}

export function OpenVault(arg1) {
  return window['go']['app']['App']['OpenVault'](arg1);
}

export function RemoveExcludedFolder(arg1) {
  return window['go']['app']['App']['RemoveExcludedFolder'](arg1);
}

export function RemoveRecentVault(arg1) {
  return window['go']['app']['App']['RemoveRecentVault'](arg1);
}

export function RemoveTagFromFile(arg1, arg2) {
  return window['go']['app']['App']['RemoveTagFromFile'](arg1, arg2);
}

export function RemoveTagsFromFiles(arg1, arg2) {
  return window['go']['app']['App']['RemoveTagsFromFiles'](arg1, arg2);
}

export function RescanVault() {
  return window['go']['app']['App']['RescanVault']();
}

export function ScanVault() {
  return window['go']['app']['App']['ScanVault']();
}

export function SearchFiles(arg1, arg2) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function SetAppSettings(arg1) {
  return window['go']['app']['App']['SetAppSettings'](arg1);
}

export function SetFavoriteForFiles(arg1, arg2) {
  return window['go']['app']['App']['SetFavoriteForFiles'](arg1, arg2);
}

export function SetRatingForFiles(arg1, arg2) {
  return window['go']['app']['App']['SetRatingForFiles'](arg1, arg2);
}

export function SetVaultConfig(arg1) {
  return window['go']['app']['App']['SetVaultConfig'](arg1);
}

export function UpdateFile(arg1) {
  return window['go']['app']['App']['UpdateFile'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['app']['App']['UpdateTag'](arg1);
}
