// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {app} from '../models';
import {config} from '../models';

export function AddExcludedFolder(arg1:string):Promise<void>;

export function AddTagToFile(arg1:number,arg2:number):Promise<void>;

export function AddTagsToFiles(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function CancelThumbnailGeneration():Promise<void>;

export function CleanupOrphanThumbnails():Promise<void>;

export function CloseVault():Promise<void>;

export function CreateTag(arg1:db.TagCreate):Promise<db.Tag>;

export function DeleteTag(arg1:number):Promise<void>;

export function GenerateThumbnail(arg1:number):Promise<string>;

export function GenerateThumbnailsForFiles(arg1:Array<number>):Promise<number>;

export function GenerateThumbnailsPool():Promise<void>;

export function GetAllTagFileCounts():Promise<Record<number, number>>;

export function GetBatchMetadata(arg1:Array<number>):Promise<Array<app.FileMetadata>>;

export function GetCurrentVault():Promise<db.VaultInfo>;

export function GetExcludedFolders():Promise<Array<string>>;

export function GetFileByID(arg1:number):Promise<db.File>;

export function GetFileMetadata(arg1:number):Promise<app.FileMetadata>;

export function GetFileTags(arg1:number):Promise<Array<db.Tag>>;

export function GetFiles(arg1:db.FileFilter,arg2:db.SortOpts,arg3:number,arg4:number):Promise<db.FilePage>;

export function GetFolderTree(arg1:string):Promise<db.FolderNode>;

export function GetLastVaultPath():Promise<string>;

export function GetOriginalFilePath(arg1:number):Promise<string>;

export function GetTagFileCount(arg1:number):Promise<number>;

export function GetTags(arg1:string):Promise<Array<db.Tag>>;

export function GetThumbnailData(arg1:number):Promise<string>;

export function GetThumbnailInfo(arg1:number):Promise<app.ThumbnailInfo>;

export function GetThumbnailPath(arg1:number):Promise<string>;

export function GetVaultConfig():Promise<config.VaultConfig>;

export function OpenVault(arg1:string):Promise<db.VaultInfo>;

export function RemoveExcludedFolder(arg1:string):Promise<void>;

export function RemoveTagFromFile(arg1:number,arg2:number):Promise<void>;

export function RemoveTagsFromFiles(arg1:Array<number>,arg2:Array<number>):Promise<void>;

export function RescanVault():Promise<number>;

export function ScanVault():Promise<number>;

export function SearchFiles(arg1:string,arg2:number):Promise<Array<db.File>>;

export function SelectFolder():Promise<string>;

export function SetFavoriteForFiles(arg1:Array<number>,arg2:number):Promise<void>;

export function SetRatingForFiles(arg1:Array<number>,arg2:number):Promise<void>;

export function SetVaultConfig(arg1:config.VaultConfig):Promise<void>;

export function UpdateFile(arg1:db.FileUpdate):Promise<void>;

export function UpdateTag(arg1:db.TagUpdate):Promise<void>;
